#!/bin/sh
username=${0##*/}
log() { logger -p user.info -t "${username}[$$]" "$*"; }
IFACE=$1
ACTION=$2

case ${IFACE} in
    eth*|usb*|en*|net*)
        case ${ACTION} in
            up)
                log "disabling wifi radio"
                nmcli radio wifi off
                ;;
            down)
                log "enabling wifi radio"
                nmcli radio wifi on
                ;;
        esac
        ;;
esac
